# The .NET Core application. This was mostly built from:https://www.freecodecamp.org/news/run-multiple-containers-with-docker-compose/ 
version: '3.4'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      Windows_Authentication: "false"
      MSSQL_SA_PASSWORD: "YourGonnaBurnAlright1234"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
    expose: 
      - '1433'
  # And the Kestral certificate stuff was a helpful effort from Albert Rise Nielsen : https://github.com/albe2669
  dotnet:
    depends_on: 
      - db
    build: ./
    environment: 
      ASPNETCORE_URLS: https://+:5273;http://+:7102
      ASPNETCORE_HTTPS_PORT: 5273
      ASPNETCORE_Kestrel__Certificates__Default__Password_FILE: ./cert_scripts/cert_password.txt
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/cert.pfx
    ports:
      - "7102:7102"
      - "5273:5273"
    volumes:
      - './.local:/https/'
      - 'cert_scripts:/cert_scripts'
    