version: '3.4'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      Windows_Authentication: "false"
      MSSQL_SA_PASSWORD: "YourGonnaBurnAlright1234"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
    expose: 
      - '1433'
  dotnet:
    depends_on: 
      - db
    build: ./
    environment: 
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
    ports:
      - "7102:80"
      - "5273:443"
    #volumes: 
    #  - /home/slug/certs/
    #  - "8080:1433"
    #expose:
    #  - "8080"
    #  - "1433"
    
    