version: '3.4'
services:
  super-app-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    ports:
      - '5000:5000'
    expose:
      - '5000'
  super-app-dotnet:
    build: ./
    ports:
      - "8080:5273"