version: '3.4'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      Windows_Authentication: "false"
      MSSQL_SA_PASSWORD: "YourGonnaBurnAlright1234"
      ACCEPT_EULA: "Y"
    ports:
      - '1433:1433'
    expose: 
      - '1433'
  dotnet:
    depends_on: 
      - db
    build: ./
    #ports:
    #  - "8081:5273"
    #  - "8080:1433"
    #expose:
    #  - "8080"
    #  - "1433"
    
    