@startuml

header Sequence Diagram for Message- and Datataflow
Title Accessing Public Timeline As An Unauthorized User


actor "Unauthorized User" as UnauthorizedUser
participant "Front End" as Fe
participant "API" as Api
participant "Data-handler" as Dh
database "Database" as Db 

@enduml