@startuml
header UML Activity Diagram for Github Actions
title Azure Pipeline / Database Update (azure_pipeline.yml)
start
legend top left
Legend:
⨂ : termination of workflow
⚫ : start of workflow
◉ : stop and completion of workflow
Yellow box with ... : repeation of succes if-else block
endlegend

:Checkout Github Branch (The Branch that got pushed to);


if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif


:Setup Dotnet 7 SDK;

#yellow:...;

:Install Dotnet Entity Framework (dotnet tool install);

#yellow:...;

:Install Azure CLI tool (az);

#yellow:...;

:Login to Azure CLI (az login);

#yellow:...;

:Create EF migration bundle;

#yellow:...;

:Apply the migration bundle to the database using az CLI;

#yellow:...;

:Logout from Azure CLI (az logout);

#yellow:...;

#green:Sucessfully Updated Database;

stop
@enduml