@startuml
header UML Activity Diagram for Github Actions
title Build And Test Workflow (build_and_test.yml)
start
legend top left
Legend:
⨂ : termination of workflow
⚫ : start of workflow
◉ : stop and completion of workflow
Yellow box with ... : repeation of success error decision
endlegend

:Checkout Github Branch (The Branch that got pushed to);


if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif


:Setup Dotnet 7 SDK;

#yellow:...;

:Restore dependencies (dotnet restore);

#yellow:...;

:Build (dotnet build);

#yellow:...;

:Run Tests (dotnet test);

#yellow:...;

#green:Tests passed;

stop
@enduml
