@startuml
header UML Activity Diagram for Github Actions
title Playwright Workflow (playwright.yml)
start
legend top left
Legend:
⨂ : termination of workflow
⚫ : start of workflow
◉ : stop and completion of workflow
Yellow box with ... : repeation of success error decision
endlegend

:Checkout Github Branch (The Branch that got pushed to);


if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif


:Setup Dotnet 7 SDK;

#yellow:...;

:Install powershell (dotnet tool install);

#yellow:...;

:Install Docker (Ubuntu docker install);

#yellow:...;

:Install Playwright (dotnet add packages);

#yellow:...;

:Build Project (dotnet build);

#yellow:...;

:Install Playwright Browsers (using powershell);

#yellow:...;

:Generate Browser Certificates (using bash script);

#yellow:...;

:Start Program and Database using docker-compose;

#yellow:...;

:Wait 15 seconds for the program to start;

:Run Playwright Tests (dotnet test);

#yellow:...;

#green:Tests Passed;

stop
@enduml