@startuml
header UML Activity Diagram for Github Actions
title Playwright Workflow (playwright.yml)
start
:Checkout Github Branch (The Branch that got pushed to);


if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif


:Setup Dotnet 7 SDK;

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Install powershell (dotnet tool install);

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Install Docker (Ubuntu docker install);

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Install Playwright (dotnet add packages);

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Build Project (dotnet build);

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Install Playwright Browsers (using powershell);

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Generate Browser Certificates (using bash script);

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Start Program and Database using docker-compose;

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Wait 15 seconds for the program to start;

:Run Playwright Tests (dotnet test);

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

#green:Tests Passed;

stop
@enduml