@startuml team_workflow
header Activity diagram for group's workflow
title Group's work activities 
start
:Task is thought off or given;
:Issue is written;
:Members are assigned;
:Issue is moved to "Being planned";
:Solution is planned;
:A feature branch is created; 
repeat
    :Issue is moved to "Being build";
    fork
        :Solution is build;
    fork again
        :Issue is updated;
    endfork
    :Pull-request is opened;
    :Issue is moved to "In review";
    :Team members review the pull-requst;
repeat while (Aprroved for merge?) is (No)
->Yes;
:Merge pull-request;
:Issue is moved to "Done";
stop
@enduml