@startuml user_activities_legend
header User activities legend
title Legend for User activities activity diagram
stop
note right: Goes back to diagram beginning
 #23d96c:      ;
note right: Page
kill
 #955acc:      ;
note right: Page element the user looks at
kill
 #4fa7c9:      ;
note right: User action or button
kill
 #bf4a3d:      ;
note right: Process
kill
@enduml