@startuml user_activities_digram_authorized
header UML Activity Digram for user activities
title User is authorrized
start
floating note left: When the program stops that means the user\nis no longer authorized and the the program\ngoes back to the root page as an unauthorized user
repeat
    :Open root page;
    partition "**process** login" {
        :Click "login";
        :Login to GitHub;
        :Authorize Chirp on GitHub;
}
repeat while (succes?) is (No)
->Yes;
switch (looking at public timeline)
case (Read cheeps)
    :Brows cheeps on the
    first page on public timeline;
    :Look at new page number
    on author timeline;
case (Go to to authors timeline)
    :Borws cheeps on 
    authors timeline;
    :Look at new page number 
    on author timeline;
case (Go to hashtag page)
    :Brows cheeps with 
    selected hashtag;
case (Follow author)
    :Author is added to your follows;
    :See followed authors cheeps on
    own timeline;
case (Unfollow author)
    :Author is removed from
    your follows;
    :No longer see unfollowed
    authors cheeps on own timeline;
case (Upvote cheep)
    if (Already upvote?) then (Yes)
        :Remove upvote;
    else (No)
        :Add upvote to cheep;
    endif
case (Downvote cheep)
    if (Already downvoted?) then (Yes)
        :Remove downvote from cheep;
    else (No)
        :Add downvote from cheep;
    endif
case (Post cheep)
    :Write a cheep from either
    public or author timeline;
    if (YouTube link?) then (Yes)
        :Add link to YouTube video;
    else (No)
    endif
    if (Hashtags?) then (Yes)
        :Add hashtag to cheep by 
        adding "#<hashtag_text>";
    else (No)
    endif
    :Click "Share";
case (Go to profile page)
    :Open profile page;
    switch (Looking at profile page)
    case (See user info)
        :See information about the user;
    case (Download user data)
        :Download a file of all the user
        data that chirp has on the user;
    case (Delete user data)
        :Click "Forget me";
        :Compleatly removes the user from
        chirps database;
        stop
    case (See following)
        :See authors that use follows;
    case (See cheeps)
        :See all cheeps made the user;
    case (Email)
        if (Has email) then (Yes)
            :Add an email;
        else (No)
            :Update current email;
        endif
    endswitch
endswitch
stop
@enduml