@startuml

header Sequence Diagram for Message- and Datataflow
Title Accessing Public Timeline As An Unauthorized User

actor "User" as Us
participant "Front End" as Fe
participant "API" as Api
participant "Data-handler" as Dh
database "Database" as Db 

skinparam legend {
  backgroundColor #E6E6E6
  entrySeparator #E6E6E6
  borderColor #FFFFFF
}

legend top

  <b>Legend</b>

  Lifelines
  |     <#LightBlue>       | Async method's lifeline |
  |     <#white>           | Async method's lifeline, nested |

  Arrow-heads
  |    <size:24><&arrow-right></size>|  Synchronous method |
  |    <size:20><U+2192></size>      |  Async methods |

  Other
  | <b>alt</b>-box | Occurs if [condition] is true |
endlegend

Us -> Fe: Accesses webpage
Fe -> Api: HTTP GET: {url}/
Activate Api #LightBlue
    Api ->> Dh: GetSome(32, 0)
    Activate Api 
        Dh -> Db: Queries 32 newest cheeps
        Db --> Dh: Returns:\nUp to 32 newest cheeps,\nand count of all cheeps
        Dh -->> Api: Returns:\nPaginated list of cheeps sorted by date,\nand count of all cheeps
    Deactivate Api
Deactivate Api
Api --> Fe: HTTP Response:\ntext/html with cheeps
Fe --> Us: Renders webpage
@enduml