@startuml
header UML Activity Diagram for Github Actions
title Build And Test Workflow (build_and_test.yml)
start
:Checkout Github Branch (The Branch that got pushed to);


if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif


:Setup Dotnet 7 SDK;

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Restore dependencies (dotnet restore);

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Build (dotnet build);

if(Succes) then (No)
    #pink:Error;
    end
else (Yes)
endif

:Run Tests (dotnet test);

if(Tests Passed) then (No)
    #pink:Exception;
    end
else (Yes)
endif

#green:Tests passed;

stop
@enduml
