# This workflow will add issues to the project board on github


name: Move assigned card
on:
  issues:
    types:
      - opened
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          project: ITU-BDSA23-GROUP10 Chirp
          column: Not started
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: bug
          label-operator: NOT
