# This workflow will add issues to the project board on github


name: Move assigned card
on:
  issues:
    types:
      - opened
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: ITU-BDSA23-GROUP10 Chirp
          column: Not started
          repo-token: ${{ secrets.GITHUB_TOKEN }}
