name: Azure Pipeline

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # how to implement the secrets in github:
      # https://youtu.be/tXv_npAP90k?si=EMC8pgYt5paIQTZN&t=122
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      WEB_APP_NAME: ${{ secrets.WEB_APP_NAME }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install EF Tools
      run: dotnet tool install --global dotnet-ef --version 7.0.13

    - name: install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    # how to set up the yaml file with azure & github secrets: 
    # https://learn.microsoft.com/en-us/azure/azure-sql/database/connect-github-actions-sql-db?view=azuresql&tabs=userlevel
    - name: Setup Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Drop Database
      run: |
        dotnet ef database drop --project ./src/Chirp.Web

    - name: Create EF bundle
      run: dotnet ef migrations bundle --self-contained -r linux-x64 --project ./src/Chirp.Web

    - name: Apply EF migrations
      run: |
        # the --output tsv is just formatting (tab-seperated values), json is the default (might change this to json?)
        # the az command gets the password and other details directly from azure
        # --query "[0].value" --output tsv
        CONNECTION_STRING=$(az webapp config connection-string list --name $WEB_APP_NAME --resource-group $RESOURCE_GROUP --query "[0].value" --output tsv)
        # https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#bundles
        chmod +x efbundle
        ./efbundle --connection "$CONNECTION_STRING"

    - name: Logout of Azure CLI
      run: az logout

      # AZURE CREDENTIALS
      # https://learn.microsoft.com/en-us/cli/azure/install-azure-cli
      # For the azure credentials value for github it should be formatted as json
      # check in terminal you have the azure client installed by writing az version
      # insert the following command (after youre logged in): az ad sp create-for-rbac
      # dont know if i have access? command to see which subscription IDs are available:
      # az account list --output table
      # az ad sp create-for-rbac --name "chirpgroup10database" --role contributor --scopes /subscriptions/<id>/resourceGroups/<remote group name> --sdk-auth