# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    tags:
     - '*'
      branches:
        - main
    

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      shell: bash
      run:
        #Building the entire world over here and zipping it up in tar and zip
        dotnet publish src/ --framework netcoreapp3.1 --runtime "linux-x64" -c Release -o "Chirp.CLI-linux-x64"
        7z a -tzip "Chirp.CLI-linux-x64".zip "./Chirp.CLI-linux-x64/*"
        dotnet publish src/ --framework netcoreapp3.1 --runtime "win-x64" -c Release -o "Chirp.CLI-win-x64"
        7z a -tzip "Chirp.CLI-win-x64".zip "./Chirp.CLI-win-x64/*"
        dotnet publish src/ --framework netcoreapp3.1 --runtime "osx-x64" -c Release -o "Chirp.CLI-osx-x64"
        7z a -tzip "Chirp.CLI-osx-x64".zip "./Chirp.CLI-osx-x64/*"

        
        uses: softprops/action-gh-release@v1
        with:
          files: "src*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
