# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branch:
      - main
    #tags:
    # - 'v*'
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish project
      run: |
        #Building the entire world over here and zipping it up in tar and zip
<<<<<<< HEAD
        #--framework netcoreapp3.1
        dotnet publish src/ --framework netcoreapp3.1 --runtime "linux-x64" -c Release -o "Chirp.CLI-${{ github.ref }}-linux-x64"
        7z a -tzip "Chirp.CLI-${{ github.ref }}-linux-x64".zip "./Chirp.CLI-${{ github.ref }}-linux-x64/*"
        dotnet publish src/ --framework netcoreapp3.1 --runtime "win-x64" -c Release -o "Chirp.CLI-win-x64"
        7z a -tzip "Chirp.CLI-win-x64".zip "./Chirp.CLI-win-x64/*"
        dotnet publish src/ --framework netcoreapp3.1 --runtime "osx-x64" -c Release -o "Chirp.CLI-osx-x64"
        7z a -tzip "Chirp.CLI-osx-x64".zip "./Chirp.CLI-osx-x64/*"
    - name: release project
      uses: softprops/action-gh-release@v1
      with: # needed to be indented
        files: |
            linux-x64.tar.gz
            win-x64.zip
            osx-x64.tar.gz
          # was previously files: "src*"
      #repo-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
        dotnet publish src/ --framework netcoreapp3.1 --runtime "linux-x64" -c Release -o "linux-x64"
        tar -czvf "linux-x64".tar.gz "./linux-x64/*"
        dotnet publish src/ --framework netcoreapp3.1 --runtime "win-x64" -c Release -o "win-x64"
        7z a -tzip "win-x64".zip "./win-x64/*"
        dotnet publish src/ --framework netcoreapp3.1 --runtime "osx-x64" -c Release -o "osx-x64"
        tar -czvf "osx-x64".tar.gz "./osx-x64/*"
    - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: "src*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> parent of 7b59987 (Merge to pull from main)
