name: Pandoc PDF Conversion

on: 
    push:
        branches: main
        paths: 
            - 'docs/**'
                
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v3
        #- run: sudo apt-get install texlive-fonts-recommended texlive-latex-recommended
        #- uses: actions/checkout@v3
        - uses: docker://pandoc/latex:2.9
          with:
            args: "-f markdown_strict -t pdf" # gets appended to pandoc command