name: Playwright Tests
on:
  push:
    branches: [ ui-testing ]
  pull_request:
    branches: [ ui-testing ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - run: dotnet build
    - name: Ensure browsers are installed
      run: pwsh test/PlaywrightTests/bin/Debug/net8.0/playwright.ps1 install --with-deps --ignore-https-errors
    - name: Run your tests
      run: dotnet test