name: Playwright Tests
on:
  push:
    branches: [ PlaywrightGithubActionFix ]
  pull_request:
    branches: [ PlaywrightGithubActionFix ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - run: dotnet build

    - name: Install Powershell
      run: dotnet tool install --global Powershell --version 7.3.9

    - name: Install docker && compose

      #Install instructions from docker: https://docs.docker.com/engine/install/ubuntu/
      run: |
        sudo apt-get update
        sudo apt-get install ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
        
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    - name: Install Playwright
      run: dotnet add test/PlaywrightTests package Microsoft.Playwright --version 1.40.0 

    - name: Ensure browsers are installed
      run: pwsh playwright.ps1 install --with-deps --ignore-https-errors
      working-directory: test/PlaywrightTests/bin/Debug/net7.0

    - name: generate certificates
      run: chmod +x create_cert.sh && ./create_cert.sh
      working-directory: cert_scripts

    - name: Start program as a docker container
      run: docker compose up -d
      working-directory: Chirp

    - name: Wait for the program to start
      run: sleep 60

    - name: Run the tests
      run: dotnet test
      working-directory: test/PlaywrightTests